### ISSUE TITLE
Transform error. Error: undefined does not match field "name": string of type Identifier

### ISSUE THREAD

**Issue by joshunger** [mskelton/ratchet#41]
Navigate to https://mskelton.dev/ratchet

Enter the following -

```javascript
import PropTypes from "prop-types"
import React from "react"

export function MyComponent(props) {
  return <span />
}

MyComponent.propTypes = {
  bar: PropTypes.string.isRequired,
  'dashed-prop': PropTypes.number,
}
```

Error:

```javascript
Transform error. Error: undefined does not match field "name": string of type Identifier
    at n (main.ab6196fd287e15dd275b.js:2:101878)
    at main.ab6196fd287e15dd275b.js:2:102196
    at Array.forEach (<anonymous>)
    at Function.i [as identifier] (main.ab6196fd287e15dd275b.js:2:102169)
    at V (main.ab6196fd287e15dd275b.js:2:2677597)
    at Array.map (<anonymous>)
    at te (main.ab6196fd287e15dd275b.js:2:2680210)
    at e.<anonymous> (main.ab6196fd287e15dd275b.js:2:2680262)
    at main.ab6196fd287e15dd275b.js:2:2537682
    at Array.forEach (<anonymous>)
a @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
setTimeout (async)
(anonymous) @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
Vn.t @ main.ab6196fd287e15dd275b.js:2
Vn @ main.ab6196fd287e15dd275b.js:2
(anonymous) @ main.ab6196fd287e15dd275b.js:2
```

**Comment by mskelton** [comment]
Thanks for the report!  I've just pushed a fix that will resolve this issue.

**Comment by joshunger** [comment]
@mskelton thank you! Ratchet has been a huge help really appreciate it.
